# Netlify deployment configuration

[build]
  # Directory to change to before starting build
  base = "."
  
  # Directory that contains the deploy-ready files
  publish = "dist/"
  
  # Build command
  command = "npm run build"

[build.environment]
  # Node version for builds
  NODE_VERSION = "20"

# Production context
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"

# Deploy Preview context
[context.deploy-preview]
  command = "npm run build"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Redirects and headers
[[redirects]]
  # SPA redirect - all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
